import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useActions, useAppState} from "@/state";
import Link from "next/link";
import {useState} from "react";

export default function Home() {
  const appState = useAppState();
  const actions = useActions();

  const [, setRandom] = useState<number>(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Current view: <a href="#">{appState.products.list.mode}</a>
        </h1>

        <div className={styles.grid}>
          <button className={styles.card} onClick={() => {
            setRandom(Math.random());
          }}>
            <h2>Reload</h2>
            <p>Force reload.</p>
          </button>
          <button className={styles.card} onClick={async () => {
            await actions.products.setProductsDisplayMode({mode: 'cards'});
          }}>
            <h2>Cards</h2>
            <p>Switch to cards view.</p>
          </button>
          <button className={styles.card} onClick={async () => {
            await actions.products.setProductsDisplayMode({mode: 'list'});
          }}>
            <h2>List</h2>
            <p>Switch to list view.</p>
          </button>
          <Link href="/index2" className={styles.card}>
            <h2>Index2 &rarr;</h2>
            <p>Go to index2 page.</p>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
